#!/bin/sh
xcompmgr &
numlockx &
~/.pekwm/scripts/display-xset.sh &
feh --bg-scale ~/.pekwm/scripts/walls/0.jpg &
dunst &
yakuake &
#/opt/trinity/bin/kicker &
xfce4-panel &
lxpanel &
python ~/.pekwm/scripts/switchbg.py ~/.pekwm/scripts/walls/ -s 0.08 &
kwalletmanager &
knemo &
qstardict &
~/.pekwm/scripts/flipWacom.sh &
artha &
telegram-desktop &
conky  --config=/home/dh84/.conkyrc.locker &
conky --config=/home/dh84/.conkyrc.leftclockW.locker &

