#!/bin/sh
# PekWM start file
# This file is a simple shell script; It gets run on pekwm startup, after
# the theme and all config has loaded if it is set executable  (chmod +x start).
# It gets re-run every time pekwm is restarted.
#
#export DE="kde"          #removed AGAIN 2016-08 breaks menu and other functions
seq 0 1 | xargs -l1 -I@ compton -b -d :0.@ --config ~/.compton.config &
numlockx &
#
###following breaks qedit
##setxkbmap -option ctrl:nocaps &
#
###switched to the following 2 lines
##xmodmap -e "clear Lock"
##xmodmap -e "keycode 66 = Shift_L NoSymbol Shift_L"
##xmodmap -e "keycode 78 = Caps_Lock NoSymbol Caps_Lock"
###previous 3 lines moved to ~/.Xmodmap
###see https://wiki.archlinux.org/index.php/Xmodmap
###useful commands: xev, xmodmap -pke,
#
#
~/.pekwm/scripts/display-xset.sh &
feh --bg-scale ~/.pekwm/scripts/walls/0.jpg &
yakuake &
nvidia-settings
xfce4-panel &
python ~/.pekwm/scripts/switchbg.py ~/.pekwm/scripts/walls/ -s 0.10 &
kwalletmanager &
#akonadictl start &
conky &
#~/.pekwm/scripts/YADstartBaloo.sh
pnmixer &
#nextcloud &
knemo &
#~/bin/rainlendar2/rainlendar2 &
klipper &
kmix &
#gnome-activity-journal &
conky --config=/home/dh84/.conkyrc.leftclockW &
#akonaditray &
artha &
~/.pekwm/scripts/flipWacom.sh &
#gdbus call -e -d org.freedesktop.DBus -o /org/freedesktop/DBus -m org.freedesktop.DBus.StartServiceByName org.freedesktop.Tracker1 0 &
#/usr/lib/tracker-miner-fs &
#/usr/lib/tracker-extract &
#/usr/lib/tracker-miner-user-guides &
#/usr/lib/tracker-miner-apps &
#indicator-kdeconnect &


